### PR TITLE
Vanilla Webpack HMR

### PR DESCRIPTION
**Pull request by jaredpalmer**
This replaces react-hot-loader with vanilla webpack HMR as per Dan
Abramov’s latest suggestions (i.e. sunsetting react-hot-loader and
react-transform). I am not 100% sure that `redbox-react` is working
properly. However, the project does hot reload in development.

### CODE REVIEW

**Comment by jaredpalmer** [comment]
@rowellx68 any thoughts? Not sure `redbox-react` is functioning properly.

**Comment by rowellx68** [comment]
HMR works well, but you're right about `redbox-react` not working.

**Comment by jaredpalmer** [comment]
@rowellx68 should we just drop redbox react then?

**Comment by rowellx68** [comment]
It may be best to do so until a solution can be found

**Comment by jaredpalmer** [comment]
@rowellx68 Do you have time today to send a new PR for this? Currently tied up with client work.

**Comment by rowellx68** [comment]
@jaredpalmer is this branch ready to merge to master?

**Comment by jaredpalmer** [comment]
LGTM

**Pull request merged**
