### PR TITLE
Move to Webpack 2 with three shaking and the babel "env" preset

### PR DESCRIPTION
**Pull request by roderik**
Webpack 2 implementation with as little changes as possible to the way everything works right now.

Only notable changes are: 

* Latest webpack 2 version
* devtool changes to get useful sourcemaps.
* for production builds set modules to false to enable tree shaking
* use "env" preset over "2015"

__Resulting in 91% smaller filesize for the server build, and a 5,5% smaller build for the clientside. I assume the clientside difference will grow when more libraries are used.__

--------
## Webpack 1
```
$ webpack -p --config ./tools/webpack.client.prod.js && webpack -p --config ./tools/webpack.server.prod.js 
Hash: abe313f022afc1e7954c
Version: webpack 1.14.0
Time: 12028ms
                         Asset     Size  Chunks             Chunk Names
vendor_abe313f022afc1e7954c.js   229 kB       0  [emitted]  vendor
     1_6ecae176808b6f69d1d0.js  1.51 kB       1  [emitted]  
  main_96db70266c1c0db2493c.js   120 kB       2  [emitted]  main
     3_3ee56653f6a5bacffb73.js   6.9 kB       3  [emitted]  
   [0] multi vendor 88 bytes {0} [built]
   [0] multi main 28 bytes {2} [built]
    + 635 hidden modules

Hash: 336bc4aa793d981f8ac3
Version: webpack 1.14.0
Time: 6809ms
      Asset     Size  Chunks             Chunk Names
  server.js  2.64 MB       0  [emitted]  main
1.server.js  12.8 kB       1  [emitted]  
2.server.js  29.7 kB       2  [emitted]  
3.server.js  24.9 kB       3  [emitted]  
    + 230 hidden modules
✨  Done in 19.58s.
```
--------
## Webpack 2
```
$ webpack --config ./tools/webpack.client.prod.js && webpack --config ./tools/webpack.server.prod.js 
Hash: 4e5bf76d12b75c979f28
Version: webpack 2.1.0-beta.27
Time: 8281ms
                         Asset     Size  Chunks             Chunk Names
     0_6927b1102b28bad6c4bc.js  1.57 kB       0  [emitted]  
  main_79523db2a2141c0b8849.js   120 kB       1  [emitted]  main
     2_0f6d1e7a9c2c0b7905b7.js  4.03 kB       2  [emitted]  
     3_60b1af0c1f22cabd5b2f.js  3.22 kB       3  [emitted]  
vendor_4e5bf76d12b75c979f28.js   233 kB       4  [emitted]  vendor
 [633] multi main 28 bytes {1} [built]
 [634] multi vendor 88 bytes {4} [built]
    + 645 hidden modules
Hash: 0e18347e28f639e6fd94
Version: webpack 2.1.0-beta.27
Time: 4094ms
      Asset     Size  Chunks             Chunk Names
0.server.js  1.62 kB       0  [emitted]  
1.server.js  4.08 kB       1  [emitted]  
2.server.js  3.27 kB       2  [emitted]  
  server.js   232 kB       3  [emitted]  main
    + 230 hidden modules
✨  Done in 14.46s.
```

--------
## Result

A bit bigger actually for the clientside
A __factor 10__ smaller for serverside code.

--------
## Moar!

Went a bit further, and switched from the 2015 preset to the new ['env'](https://github.com/babel/babel-preset-env) preset and only compiled the source for the last 2 browser versions and the current running node version (6.9.1).

```
$ webpack --config ./tools/webpack.client.prod.js && webpack --config ./tools/webpack.server.prod.js 
Hash: c397b0bed8fc5e4a767e
Version: webpack 2.1.0-beta.27
Time: 7490ms
                         Asset     Size  Chunks             Chunk Names
     0_ee9ff08f6def932a904c.js  1.57 kB       0  [emitted]  
  main_dc1208fee8ae6fa650d4.js  96.9 kB       1  [emitted]  main
     2_379131f69d3f5c692c2f.js  4.03 kB       2  [emitted]  
     3_06124c058360595f7e15.js  3.22 kB       3  [emitted]  
vendor_c397b0bed8fc5e4a767e.js   232 kB       4  [emitted]  vendor
 [524] multi main 28 bytes {1} [built]
 [525] multi vendor 88 bytes {4} [built]
    + 536 hidden modules
Hash: c7c80d04b54b6696e816
Version: webpack 2.1.0-beta.27
Time: 4124ms
      Asset     Size  Chunks             Chunk Names
0.server.js  1.62 kB       0  [emitted]  
1.server.js  4.08 kB       1  [emitted]  
2.server.js  3.27 kB       2  [emitted]  
  server.js   232 kB       3  [emitted]  main
    + 230 hidden modules
✨  Done in 13.72s.
```

Serverside nothing gained
Clientside a gain of 5,5%

### CODE REVIEW

**Comment by roderik** [comment]
Figured out how to pipe the serverside code through webpack and to use hot reload as well. :)

**Comment by jaredpalmer** [comment]
Nice job. Will test this out right now.

**Comment by roderik** [comment]
the serverside reloading works too good. ctrl-c is not killing webpack watch

**Comment by jaredpalmer** [comment]
`--watch` on the server is probably not going to work the way you'd like it too. We'll want chokidar + nodemon. NYT does this really well with their kyt project: https://github.com/NYTimes/kyt/blob/master/packages/kyt-core/cli/actions/dev.js#L79

**Comment by roderik** [comment]
Ok, spent half a day trying to get the NYT stuff in, failed miserably. 
Removed that commit from this PR.

**Comment by jaredpalmer** [comment]
@roderik I too have spent a day or so hacking on kyt. There are some gotchas. I haven't totally nailed this down yet, but from what I gather they have totally distinct servers for front and backend compilation, but modify public paths instead of proxyinf. AFAIK The client is bundled via webpck-dev-server (as kyt allows for client-only apps) and then they run webpack target: "node", with nodemon and chokidar to trigger rebuilds on the server (by looking at the src/server folder only). The big benefit of Webpack on the server for RPS would be sourcemaps, flags, and also the ability to handle CSS / postCSS isomorphically (which many people have requested). I personally don't care for kyts emoji console stuff and error messages.

**Comment by roderik** [comment]
I used https://github.com/kriasoft/react-starter-kit/tree/master/tools in the past as well for a universal app but they use for example a homegrown router which i don't like. But their build tools are quite nice and have everything i think. 

Aside from that, this looked interesting as well: https://github.com/glenjamin/ultimate-hot-reloading-example

**Comment by jaredpalmer** [comment]
@roderik yeah, rsk runs a proxy (via [browsersync](https://github.com/kriasoft/react-starter-kit/blob/master/tools/start.js#L66)) in front of the server during development. My problem with browsersync is that it has does weird things when you try to use it with Docker.

**Comment by jaredpalmer** [comment]
@roderik  https://github.com/glenjamin/ultimate-hot-reloading-example this looks cool, but it runs `babel-node` on the server. However, I def want to play with how it uses chokidar

**Pull request closed without merging**
