### PR TITLE
ImmutableJS in Post and PostList reducers

### PR DESCRIPTION
**Pull request by rowellx68**
This PR should close issue #61.

### CODE REVIEW

**Comment by jaredpalmer** [comment]
Does it make sense to also tackle #76 here?

**Comment by rowellx68** [comment]
I'll do some research 👍

**Comment by jaredpalmer** [comment]
@rowellx68 I am actually almost done with #76 now

**Comment by sebastiancarlsson** [comment]
Is this going to be merged soon?

**Comment by jaredpalmer** [comment]
Sorry I have been MIA on this... LGTM. Happy to merge.

**Pull request merged**
